baseURL = "http://www.aixwim.cloud/"
title = "AIXWIM"
author = "Aixwim"
copyright = "Aixwim"
languageCode = "en"
theme = "tailwind"

[pagination]
pagerSize = 6
enableEmoji = true

[markup]
  _merge = "deep"
  [markup.highlight]
    noClasses = false

[params]
  description = "Aixwim personal blog"
  keywords = "blog,personal"
  info = ["Blogger"]
  avatarURL = "images/avatar.jpg"
  dateFormat = "January 2, 2006"
  since = 2024
  rtl = false
  colorScheme = "auto"
  hideColorSchemeToggle = false
  maxSeeAlsoItems = 5
  customCSS = []
  customSCSS = []
  customJS = []
  customRemoteJS = []
  outboundLinksTracking = true
  contentTypeName = "posts"

  [params.header]
    logo = "images/avatar.jpg"

  [params.footer]
    since = 2024
    poweredby = false

[services]
  [services.disqus]
    shortname = "aixwim"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
  author = "authors"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact Me"
    url = "/contact/"
    weight = 3

  [[menu.main]]
    identifier = "rss"
    name = "RSS"
    url = "https://aixwim.cloud/index.xml"
    weight = 6
    rel = "alternate"
    type = "application/rss+xml"

[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/Xyomania/"

[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/aixwim/"

[[params.social]]
  name = "Tiktok"
  icon = "fa-brands fa-tiktok fa-2x"
  weight = 3
  url = "https://tiktok.com/@aixwim/"

[languages]

  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"
    title = "AIXWIM"

  [[languages.en.menu.main]]
    name = "About"
    weight = 1
    url = "/about/"

  [[languages.en.menu.main]]
    name = "Blog"
    weight = 2
    url = "/posts/"

  [[languages.en.menu.main]]
    name = "Contact me"
    weight = 3
    url = "/contact/"

  [languages.id]
    languageName = "Indonesia"
    weight = 2
    contentDir = "content/id"
    title = "AIXWIM"

  [[languages.id.menu.main]]
    name = "Tentang"
    weight = 1
    url = "/about/"

  [[languages.id.menu.main]]
    name = "Blog"
    weight = 2
    url = "/posts/"

  [[languages.id.menu.main]]
    name = "Kontak"
    weight = 3
    url = "/contact/"

  [languages.ja]
    languageName = "日本語"
    weight = 3
    contentDir = "content/ja"
    title = "AIXWIM"

  [[languages.ja.menu.main]]
    name = "概要"
    weight = 1
    url = "/about/"

  [[languages.ja.menu.main]]
    name = "ブログ"
    weight = 2
    url = "/posts/"

  [[languages.ja.menu.main]]
    name = "お問い合わせ"
    weight = 3
    url = "/contact/"

  [languages.ru]
    languageName = "Русский"
    weight = 4
    contentDir = "content/ru"
    title = "AIXWIM"

  [[languages.ru.menu.main]]
    name = "О нас"
    weight = 1
    url = "/about/"

  [[languages.ru.menu.main]]
    name = "Блог"
    weight = 2
    url = "/posts/"

  [[languages.ru.menu.main]]
    name = "Контакты"
    weight = 3
    url = "/contact/"

  [languages.zh-cn]
    languageName = "中文 (简体)"
    weight = 5
    contentDir = "content/zh-cn"
    title = "AIXWIM"

  [[languages.zh-cn.menu.main]]
    name = "关于"
    weight = 1
    url = "/about/"

  [[languages.zh-cn.menu.main]]
    name = "博客"
    weight = 2
    url = "/posts/"

  [[languages.zh-cn.menu.main]]
    name = "联系我"
    weight = 3
    url = "/contact/"

  [languages.zh-tw]
    languageName = "中文 (繁體)"
    weight = 6
    contentDir = "content/zh-tw"
    title = "AIXWIM"

  [[languages.zh-tw.menu.main]]
    name = "關於"
    weight = 1
    url = "/about/"

  [[languages.zh-tw.menu.main]]
    name = "部落格"
    weight = 2
    url = "/posts/"

  [[languages.zh-tw.menu.main]]
    name = "聯絡我"
    weight = 3
    url = "/contact/"