baseURL = "https://www.aixwim.cloud/"
title = "AIXWIM"
author = "Aixwim"
copyright = "Aixwim"
languageCode = "en"
theme = "PaperMod"

[outputs]
  home = ["HTML", "RSS", "JSON"]  # necessary for search

[pagination]
pagerSize = 6
enableEmoji = true

[markup]
_merge = "deep"
[markup.highlight]
noClasses = false

[params]
env = "production"
description = "Aixwim personal blog covering a wide range of topics including shopping, business, finance, technology, health, entertainment, and more. Stay updated with insightful articles and tips."
keywords = ["blog", "personal blog", "shopping", "business", "finance", "games", "pets", "entertainment", "health", "technology", "sports", "travel", "food", "lifestyle", "parenting", "affiliate marketing"]
author = "Me"
images = ["/images/"]
DateFormat = "January 2, 2006"
defaultTheme = "auto"  # dark, light
disableThemeToggle = false

ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = true
disableScrollToTop = false
comments = true
hidemeta = false
hideSummary = false
showtoc = true
tocopen = true
enableInlineShortcodes = true
enableRobotsTXT = true

disqusShortname = "aixwim"

# Assets
[params.assets]
favicon = "/favicon.ico"
favicon16x16 = "/favicon-16x16.png"
favicon32x32 = "/favicon-32x32.png"
apple_touch_icon = "/apple-touch-icon.png"
safari_pinned_tab = "/favicon-96x96.png"

# Social Media Links
[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/Xyomania/"

[[params.social]]
name = "Twitter"
icon = "fa-brands fa-x-twitter fa-2x"
weight = 3
url = "https://twitter.com/aixwim/"

[[params.social]]
name = "Tiktok"
icon = "fa-brands fa-tiktok fa-2x"
weight = 3
url = "https://tiktok.com/@aixwim/"

# Profile Mode
[params.profileMode]
enabled = false
title = "Aixwim"
subtitle = "Welcome to the world of AIXWIM!"
imageUrl = "/avatar.jpg"
imageWidth = 120
imageHeight = 120
imageTitle = "Aixwim Avatar"
buttons = [{name = "Posts", url = "/posts/"}, {name = "Tags", url = "/tags/"}]

# Cover Configuration
[params.cover]
hidden = false
hiddenInList = false
hiddenInSingle = false

# Edit Post
[params.editPost]
URL = "https://github.com/Xyomania/xyomania.github.io"
Text = "Suggest Changes"
appendFilePath = true

# Search (Fuse.js options)
[fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
limit = 10
keys = ["title", "permalink", "summary", "content"]

# Menu Configuration
[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "posts"
name = "Blog"
url = "/posts/"
weight = 2

[[menu.main]]
identifier = "contact"
name = "Contact Me"
url = "/contact/"
weight = 3

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 4

[[menu.main]]
identifier = "rss"
name = "RSS"
url = "https://aixwim.cloud/index.xml"
weight = 6
rel = "alternate"
type = "application/rss+xml"

# Pygments settings
pygmentsUseClasses = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

# Languages settings
[languages]
[languages.en]
languageName = "English"
weight = 1
contentDir = "content/en"
title = "AIXWIM"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "/about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "/posts/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 3
url = "/contact/"

[[languages.en.menu.main]]
name = "Search"
weight = 4
url = "/search/"

[languages.id]
languageName = "Indonesia"
weight = 2
contentDir = "content/id"
title = "AIXWIM"

[[languages.id.menu.main]]
name = "Tentang"
weight = 1
url = "/about/"

[[languages.id.menu.main]]
name = "Blog"
weight = 2
url = "/posts/"

[[languages.id.menu.main]]
name = "Kontak"
weight = 3
url = "/contact/"

[[languages.id.menu.main]]
name = "Pencarian"
weight = 4
url = "/search/"

[languages.ja]
languageName = "日本語"
weight = 3
contentDir = "content/ja"
title = "AIXWIM"

[[languages.ja.menu.main]]
name = "概要"
weight = 1
url = "/about/"

[[languages.ja.menu.main]]
name = "ブログ"
weight = 2
url = "/posts/"

[[languages.ja.menu.main]]
name = "お問い合わせ"
weight = 3
url = "/contact/"

[[languages.ja.menu.main]]
name = "検索"
weight = 4
url = "/search/"

[languages.ru]
languageName = "Русский"
weight = 4
contentDir = "content/ru"
title = "AIXWIM"

[[languages.ru.menu.main]]
name = "О нас"
weight = 1
url = "/about/"

[[languages.ru.menu.main]]
name = "Блог"
weight = 2
url = "/posts/"

[[languages.ru.menu.main]]
name = "Контакты"
weight = 3
url = "/contact/"

[[languages.ru.menu.main]]
name = "Поиск"
weight = 4
url = "/search/"

[languages.zh-cn]
languageName = "中文 (简体)"
weight = 5
contentDir = "content/zh-cn"
title = "AIXWIM"

[[languages.zh-cn.menu.main]]
name = "关于"
weight = 1
url = "/about/"

[[languages.zh-cn.menu.main]]
name = "博客"
weight = 2
url = "/posts/"

[[languages.zh-cn.menu.main]]
name = "联系我"
weight = 3
url = "/contact/"

[[languages.zh-cn.menu.main]]
name = "搜索"
weight = 4
url = "/search/"

[languages.zh-tw]
languageName = "中文 (繁體)"
weight = 6
contentDir = "content/zh-tw"
title = "AIXWIM"

[[languages.zh-tw.menu.main]]
name = "關於"
weight = 1
url = "/about/"

[[languages.zh-tw.menu.main]]
name = "部落格"
weight = 2
url = "/posts/"

[[languages.zh-tw.menu.main]]
name = "聯絡我"
weight = 3
url = "/contact/"

[[languages.zh-tw.menu.main]]
name = "搜尋"
weight = 4
url = "/search/"
