baseURL = "http://www.aixwim.cloud/"
title = "AIXWIM"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
[pagination]
pagerSize = 6
enableEmoji = true

[services]
[services.disqus]
# Enable Disqus comments
shortname = "aixwim"

[markup.highlight]
noClasses = false

[params]
author = "Aixwim"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Aixwim personal blog"
keywords = "blog,personal"
info = ["Blogger"]
avatarURL = "images/avatar.jpg"
# gravatar = "gravatar.com/aixwim"
dateFormat = "January 2, 2006"
since = 2024
# Git Commit in Footer, uncomment the line below to enable it
# commit = ""
# Right To Left, shift content direction for languages such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# serverURL = "analytics.example.com" # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
 outboundLinksTracking = true
# fileDownloadsTracking = true

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
# code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
# [params.googleTagManager]
# id = "gid"

# If you want to use Yandex Metrika(https://metrika.yandex.ru) for analytics, add this section
# [params.yandexMetrika]
# id = "gid"

# If you want to use Application Insights(https://azure.com/) for analytics, add this section
# [params.applicationInsights]
# connectionString = "connectionString"

# If you want to use microanalytics.io for analytics, add this section
# [params.microAnalytics]
# id = "ABCDE"
# dnt = "false" # respect DNT tracker, "true" by default

# If you want to use Pirsch(https://pirsch.io) for analytics, add this section
# [params.pirsch]
# code = "ABCDE"

# If you want to use Umami(https://umami.is) for analytics, add this section
# [params.umami]
# siteID = "ABCDE"
# scriptURL = "analytics.REGION.umami.is/SCRIPTNAME.js"

# If you want to implement a Content-Security-Policy, add this section
# [params.csp]
# childsrc = ["'self'"]
# fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
# formaction = ["'self'"]
# framesrc = ["'self'", "https://www.youtube.com"]
# imgsrc = ["'self'"]
# objectsrc = ["'none'"]
 stylesrc = [
   "'self'",
   "'unsafe-inline'",
   "https://fonts.googleapis.com/",
   "https://cdn.jsdelivr.net/",
 ]
# scriptsrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://www.google-analytics.com",
#   "https://cdn.jsdelivr.net/",
# ]
# prefetchsrc = ["'self'"]
# # connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
# connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/Xyomania/"

[[params.social]]
name = "Twitter"
icon = "fa-brands fa-x-twitter fa-2x"
weight = 3
url = "https://twitter.com/aixwim/"

[[params.social]]
name = "Tiktok"
icon = "fa-brands fa-tiktok fa-2x"
weight = 3
url = "https://tiktok.com/@aixwim/"

[[params.social]]
name = "RSS"
icon = "fa-solid fa-rss fa-2x"
weight = 6
url = "https://aixwim.cloud/index.xml"
rel = "alternate"
type = "application/rss+xml"


[languages.en]
    languageName = "English"
    weight = 1
[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 3
url = "contact/"

[languages.id]
languageName = "Indonesia"
title = "AIXWIM"
weight = 2

[languages.id.params]
author = "Aixwim"
info = "Blogger"
description = "Aixwim blog pribadi"
keywords = "blog,pribadi"

[[languages.id.menu.main]]
name = "Tentang"
weight = 1
url = "about/"

[[languages.id.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.id.menu.main]]
name = "Kontak"
weight = 3
url = "contact/"

[languages.ja.params]
author = "Aixwim"
info = "ブロガー"
description = "Aixwimの個人ブログ"
keywords = "ブログ,個人"

[languages.ja]
languageName = "日本語"
title = "AIXWIM"
weight = 3

[[languages.ja.menu.main]]
name = "概要"
weight = 1
url = "about/"

[[languages.ja.menu.main]]
name = "ブログ"
weight = 2
url = "posts/"

[[languages.ja.menu.main]]
name = "お問い合わせ"
weight = 3
url = "contact/"

[languages.ru.params]
author = "Aixwim"
info = "Блогер"
description = "Личный блог Aixwim"
keywords = "блог,личный"


[languages.ru]
languageName = "Русский"
title = "AIXWIM"
weight = 4

[[languages.ru.menu.main]]
name = "О нас"
weight = 1
url = "about/"

[[languages.ru.menu.main]]
name = "Блог"
weight = 2
url = "posts/"

[[languages.ru.menu.main]]
name = "Контакты"
weight = 3
url = "contact/"

[languages.zh-cn.params]
author = "Aixwim"
info = "博主"
description = "Aixwim的个人博客"
keywords = "博客,个人"


[languages.zh-cn]
languageName = "中文 (简体)"
title = "AIXWIM"
weight = 5

[[languages.zh-cn.menu.main]]
name = "关于"
weight = 1
url = "about/"

[[languages.zh-cn.menu.main]]
name = "博客"
weight = 2
url = "posts/"

[[languages.zh-cn.menu.main]]
name = "联系我"
weight = 3
url = "contact/"

[languages.zh-tw.params]
author = "Aixwim"
info = "部落客"
description = "Aixwim的個人部落格"
keywords = "部落格,個人"


[languages.zh-tw]
languageName = "中文 (繁體)"
title = "AIXWIM"
weight = 6

[[languages.zh-tw.menu.main]]
name = "關於"
weight = 1
url = "about/"

[[languages.zh-tw.menu.main]]
name = "部落格"
weight = 2
url = "posts/"

[[languages.zh-tw.menu.main]]
name = "聯絡我"
weight = 3
url = "contact/"
