baseURL = "https://www.aixwim.cloud/"
title = "AIXWIM"
author = "Aixwim"
copyright = "Aixwim"
languageCode = "en"
theme = "PaperMod"

[outputs]
home = ["HTML", "RSS", "JSON"] # Mendukung pencarian dan format lainnya.

[pagination]
pagerSize = 6
enableEmoji = true

[markup]
_merge = "deep"

[markup.highlight]
noClasses = false

[params]
env = "production"
description = "Aixwim personal blog covering a wide range of topics including shopping, business, finance, technology, health, entertainment, and more. Stay updated with insightful articles and tips."
keywords = ["blog", "personal blog", "shopping", "business", "finance", "games", "pets", "entertainment", "health", "technology", "sports", "travel", "food", "lifestyle", "parenting", "affiliate marketing"]
author = "Aixwim"
images = ["/images/"]
DateFormat = "January 2, 2006"
defaultTheme = "auto" # dark, light
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = true
disableScrollToTop = false
comments = true
hidemeta = false
hideSummary = false
showtoc = true
tocopen = true
enableInlineShortcodes = true
enableRobotsTXT = true
disqusShortname = "aixwim"
yandexVerification = "705ee09bd561a459"

[params.analytics.google]
MeasurementID = "G-PWLWH73DHK"

[params.assets]
favicon = "/favicon.ico"
favicon16x16 = "/favicon-16x16.png"
favicon32x32 = "/favicon-32x32.png"
apple_touch_icon = "/apple-touch-icon.png"
safari_pinned_tab = "/favicon-96x96.png"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/Xyomania/"

[[params.social]]
name = "Twitter"
icon = "fa-brands fa-x-twitter fa-2x"
weight = 2
url = "https://twitter.com/aixwim/"

[[params.social]]
name = "Tiktok"
icon = "fa-brands fa-tiktok fa-2x"
weight = 3
url = "https://tiktok.com/@aixwim/"

[params.profileMode]
enabled = false
title = "Aixwim"
subtitle = "Welcome to the world of AIXWIM!"
imageUrl = "/avatar.jpg"
imageWidth = 120
imageHeight = 120
imageTitle = "Aixwim Avatar"
buttons = [
  {name = "Posts", url = "/posts/"},
  {name = "Tags", url = "/tags/"}
]

[params.cover]
hidden = false
hiddenInList = false
hiddenInSingle = false

[params.editPost]
URL = "https://github.com/Xyomania/xyomania.github.io"
Text = "Suggest Changes"
appendFilePath = true

[fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
limit = 10
keys = ["title", "permalink", "summary", "content"]


[markup.pygments]
pygmentsUseClasses = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[languages]
[languages.en]
languageName = "English"
weight = 1
contentDir = "content/en"
title = "AIXWIM"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "/about/"
[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "/posts/"
[[languages.en.menu.main]]
name = "Categories"
weight = 3
url = "/categories/"
[[languages.en.menu.main]]
name = "Contact"
weight = 4
url = "/contact/"
[[languages.en.menu.main]]
name = "Search"
weight = 5
url = "/search/"
[[languages.en.menu.main]]
name = "Tags"
weight = 6
url = "/tags/"

[languages.id]
languageName = "Bahasa Indonesia"
weight = 2
contentDir = "content/id"
title = "AIXWIM"

[[languages.id.menu.main]]
name = "Tentang"
weight = 1
url = "/tentang/"
[[languages.id.menu.main]]
name = "Blog"
weight = 2
url = "/pos/"
[[languages.id.menu.main]]
name = "Kategori"
weight = 3
url = "/kategori/"
[[languages.id.menu.main]]
name = "Kontak"
weight = 4
url = "/kontak/"
[[languages.id.menu.main]]
name = "Pencarian"
weight = 5
url = "/pencarian/"
[[languages.id.menu.main]]
name = "Tag"
weight = 6
url = "/tag/"

[languages.ja]
languageName = "日本語"
weight = 3
contentDir = "content/ja"
title = "AIXWIM"

[[languages.ja.menu.main]]
name = "概要"
weight = 1
url = "/概要/"
[[languages.ja.menu.main]]
name = "ブログ"
weight = 2
url = "/ブログ/"
[[languages.ja.menu.main]]
name = "カテゴリー"
weight = 3
url = "/カテゴリー/"
[[languages.ja.menu.main]]
name = "連絡先"
weight = 4
url = "/連絡先/"
[[languages.ja.menu.main]]
name = "検索"
weight = 5
url = "/検索/"
[[languages.ja.menu.main]]
name = "タグ"
weight = 6
url = "/タグ/"

[languages.ru]
languageName = "Русский"
weight = 4
contentDir = "content/ru"
title = "AIXWIM"

[[languages.ru.menu.main]]
name = "О нас"
weight = 1
url = "/о-нас/"
[[languages.ru.menu.main]]
name = "Блог"
weight = 2
url = "/блог/"
[[languages.ru.menu.main]]
name = "Категории"
weight = 3
url = "/категории/"
[[languages.ru.menu.main]]
name = "Контакты"
weight = 4
url = "/контакты/"
[[languages.ru.menu.main]]
name = "Поиск"
weight = 5
url = "/поиск/"
[[languages.ru.menu.main]]
name = "Теги"
weight = 6
url = "/теги/"

[languages.zh-cn]
languageName = "简体中文"
weight = 5
contentDir = "content/zh-cn"
title = "AIXWIM"

[[languages.zh-cn.menu.main]]
name = "关于"
weight = 1
url = "/关于/"
[[languages.zh-cn.menu.main]]
name = "博客"
weight = 2
url = "/博客/"
[[languages.zh-cn.menu.main]]
name = "分类"
weight = 3
url = "/分类/"
[[languages.zh-cn.menu.main]]
name = "联系"
weight = 4
url = "/联系/"
[[languages.zh-cn.menu.main]]
name = "搜索"
weight = 5
url = "/搜索/"
[[languages.zh-cn.menu.main]]
name = "标签"
weight = 6
url = "/标签/"

[languages.zh-tw]
languageName = "繁體中文"
weight = 6
contentDir = "content/zh-tw"
title = "AIXWIM"

[[languages.zh-tw.menu.main]]
name = "關於"
weight = 1
url = "/關於/"
[[languages.zh-tw.menu.main]]
name = "部落格"
weight = 2
url = "/部落格/"
[[languages.zh-tw.menu.main]]
name = "分類"
weight = 3
url = "/分類/"
[[languages.zh-tw.menu.main]]
name = "聯絡"
weight = 4
url = "/聯絡/"
[[languages.zh-tw.menu.main]]
name = "搜尋"
weight = 5
url = "/搜尋/"
[[languages.zh-tw.menu.main]]
name = "標籤"
weight = 6
url = "/標籤/"
