name: Deploy Hugo

on:
  push:
    branches:
      - main  # Sesuaikan jika branch utama Anda berbeda

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
